import { User, Post, Story, Community, ChatConversation } from '../types';

// Added passwords for mock users and follower data
export const mockUsers: User[] = [
  { id: 'u1', name: 'Alex Nova', password: 'password123', nickname: 'Alex', avatarUrl: 'https://i.pravatar.cc/150?u=1', bio: 'Digital creator | Tech enthusiast | Coffee lover', followers: [], following: [] },
  { id: 'u2', name: 'Mia Jupiter', password: 'password123', nickname: 'Mia', avatarUrl: 'https://i.pravatar.cc/150?u=2', bio: 'Exploring the world, one photo at a time.', followers: [], following: [] },
  { id: 'u3', name: 'Leo Orion', password: 'password123', nickname: 'Leo', avatarUrl: 'https://i.pravatar.cc/150?u=3', bio: 'Skater and artist.', followers: [], following: [] },
  { id: 'u4', name: 'Chloe Astra', password: 'password123', nickname: 'Chloe', avatarUrl: 'https://i.pravatar.cc/150?u=4', bio: 'Just a girl who loves stars.', followers: [], following: [] },
  { id: 'u5', name: 'Sam Comet', password: 'password123', nickname: 'Sam', avatarUrl: 'https://i.pravatar.cc/150?u=5', bio: 'Musician. DM for collabs.', followers: [], following: [] },
  { id: 'u6', name: 'Ruby Nebula', password: 'password123', nickname: 'Ruby', avatarUrl: 'https://i.pravatar.cc/150?u=6', bio: 'Fashion & Lifestyle', followers: [], following: [] },
];

export const mockPosts: Post[] = [
  // Posts are now generated by users. This is intentionally left empty.
];

export const mockStories: Story[] = [
   // Stories are now generated by users. This is intentionally left empty.
];

export const mockCommunities: Community[] = [
  { id: 'c1', name: 'Digital Art Collective', description: 'Share your latest digital creations and get feedback.', bannerUrl: 'https://picsum.photos/seed/c1/800/400', members: 12800 },
  { id: 'c2', name: 'Indie Game Devs', description: 'A hub for indie game developers to collaborate and showcase.', bannerUrl: 'https://picsum.photos/seed/c2/800/400', members: 45000 },
  { id: 'c3', name: 'Urban Explorers', description: 'Discovering the hidden corners of our cities.', bannerUrl: 'https://picsum.photos/seed/c3/800/400', members: 23000 },
  { id: 'c4', name: 'Synthwave & Retrofuturism', description: 'For lovers of neon grids and 80s aesthetics.', bannerUrl: 'https://picsum.photos/seed/c4/800/400', members: 56000 },
];

export const mockConversations: ChatConversation[] = [
    // Conversations are now user-driven. This is intentionally left empty.
];