import { User, Post, Story, Community, ChatConversation } from '../types';

// Users are now added via the signup flow. The app will start with no users.
export const mockUsers: User[] = [];

export const mockPosts: Post[] = [
  // Posts are now generated by users. This is intentionally left empty.
];

export const mockStories: Story[] = [
   // Stories are now generated by users. This is intentionally left empty.
];

export const mockCommunities: Community[] = [
  { id: 'c1', name: 'Digital Art Collective', description: 'Share your latest digital creations and get feedback.', bannerUrl: 'https://picsum.photos/seed/c1/800/400', members: 12800 },
  { id: 'c2', name: 'Indie Game Devs', description: 'A hub for indie game developers to collaborate and showcase.', bannerUrl: 'https://picsum.photos/seed/c2/800/400', members: 45000 },
  { id: 'c3', name: 'Urban Explorers', description: 'Discovering the hidden corners of our cities.', bannerUrl: 'https://picsum.photos/seed/c3/800/400', members: 23000 },
  { id: 'c4', name: 'Synthwave & Retrofuturism', description: 'For lovers of neon grids and 80s aesthetics.', bannerUrl: 'https://picsum.photos/seed/c4/800/400', members: 56000 },
];

export const mockConversations: ChatConversation[] = [
    // Conversations are now user-driven. This is intentionally left empty.
];